/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by src/scripts/build-pure-ui-registry.ts
// Do not edit this file directly.
import * as React from "react"


export const Index: Record<string, any> = {
  "accordion": {
    name: "accordion",
    description: "A customizable button component",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["class-variance-authority","clsx","tailwind-merge","@base-ui-components/react","motion"],
    files: [{
      path: "src/registry/default/components/ui/accordion/index.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/ui/accordion/index.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "button": {
    name: "button",
    description: "A customizable button component",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["class-variance-authority","clsx","tailwind-merge","@radix-ui/react-slot"],
    files: [{
      path: "src/registry/default/components/ui/button/index.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/ui/button/index.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "card": {
    name: "card",
    description: "A customizable card component",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["clsx","tailwind-merge","@radix-ui/react-slot"],
    files: [{
      path: "src/registry/default/components/ui/card/index.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/ui/card/index.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "checkbox": {
    name: "checkbox",
    description: "A customizable checkbox component",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["class-variance-authority","clsx","tailwind-merge","@base-ui-components/react"],
    files: [{
      path: "src/registry/default/components/ui/checkbox/index.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/ui/checkbox/index.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dialog": {
    name: "dialog",
    description: "A customizable dialog component",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["class-variance-authority","clsx","tailwind-merge","@base-ui-components/react","motion"],
    files: [{
      path: "src/registry/default/components/ui/dialog/index.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/ui/dialog/index.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "input-otp": {
    name: "input-otp",
    description: "A customizable input OTP component",
    type: "registry:ui",
    registryDependencies: undefined,
    dependencies: ["class-variance-authority","clsx","tailwind-merge","input-otp","motion"],
    files: [{
      path: "src/registry/default/components/ui/input-otp/index.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/ui/input-otp/index.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "accordion-demo": {
    name: "accordion-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["accordion"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/accordion/accordion-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/accordion/accordion-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "accordion-variant-demo": {
    name: "accordion-variant-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["accordion"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/accordion/accordion-variant-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/accordion/accordion-variant-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "accordion-multiple-expanded-demo": {
    name: "accordion-multiple-expanded-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["accordion"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/accordion/accordion-multiple-expanded-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/accordion/accordion-multiple-expanded-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "accordion-custom-indicator-demo": {
    name: "accordion-custom-indicator-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["accordion"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/accordion/accordion-custom-indicator-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/accordion/accordion-custom-indicator-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "accordion-disabled-state-demo": {
    name: "accordion-disabled-state-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["accordion"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/accordion/accordion-disabled-state-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/accordion/accordion-disabled-state-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "accordion-reduce-motion-demo": {
    name: "accordion-reduce-motion-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["accordion"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/accordion/accordion-reduce-motion-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/accordion/accordion-reduce-motion-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "accordion-fade-demo": {
    name: "accordion-fade-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["accordion"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/accordion/accordion-fade-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/accordion/accordion-fade-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "accordion-perspective-demo": {
    name: "accordion-perspective-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["accordion"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/accordion/accordion-perspective-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/accordion/accordion-perspective-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "accordion-perspective-blur-demo": {
    name: "accordion-perspective-blur-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["accordion"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/accordion/accordion-perspective-blur-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/accordion/accordion-perspective-blur-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "accordion-scale-demo": {
    name: "accordion-scale-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["accordion"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/accordion/accordion-scale-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/accordion/accordion-scale-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "accordion-slide-demo": {
    name: "accordion-slide-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["accordion"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/accordion/accordion-slide-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/accordion/accordion-slide-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "button-demo": {
    name: "button-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/button/button-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/button/button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "button-reduce-motion-demo": {
    name: "button-reduce-motion-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/button/button-reduce-motion-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/button/button-reduce-motion-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "button-size-demo": {
    name: "button-size-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/button/button-size-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/button/button-size-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "button-variants-demo": {
    name: "button-variants-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/button/button-variants-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/button/button-variants-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "button-radius-demo": {
    name: "button-radius-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/button/button-radius-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/button/button-radius-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "button-pending-demo": {
    name: "button-pending-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/button/button-pending-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/button/button-pending-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "card-demo": {
    name: "card-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["card"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/card/card-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/card/card-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "card-variants-demo": {
    name: "card-variants-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["card"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/card/card-variants-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/card/card-variants-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "card-horizontal-layout": {
    name: "card-horizontal-layout",
    description: "",
    type: "registry:example",
    registryDependencies: ["card"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/card/card-horizontal-layout.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/card/card-horizontal-layout.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "card-with-image-demo": {
    name: "card-with-image-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["card"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/card/card-with-image-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/card/card-with-image-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "card-with-background-images-demo": {
    name: "card-with-background-images-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["card"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/card/card-with-background-images-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/card/card-with-background-images-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "checkbox-demo": {
    name: "checkbox-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["checkbox"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/checkbox/checkbox-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/checkbox/checkbox-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "checkbox-disabled-demo": {
    name: "checkbox-disabled-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["checkbox"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/checkbox/checkbox-disabled-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/checkbox/checkbox-disabled-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "checkbox-icons-demo": {
    name: "checkbox-icons-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["checkbox"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/checkbox/checkbox-icons-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/checkbox/checkbox-icons-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "checkbox-radius-demo": {
    name: "checkbox-radius-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["checkbox"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/checkbox/checkbox-radius-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/checkbox/checkbox-radius-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "checkbox-sizes-demo": {
    name: "checkbox-sizes-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["checkbox"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/checkbox/checkbox-sizes-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/checkbox/checkbox-sizes-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dialog-demo": {
    name: "dialog-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["dialog"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/dialog/dialog-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/dialog/dialog-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dialog-non-dismissible-demo": {
    name: "dialog-non-dismissible-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["dialog"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/dialog/dialog-non-dismissible-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/dialog/dialog-non-dismissible-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dialog-non-modal-demo": {
    name: "dialog-non-modal-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["dialog"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/dialog/dialog-non-modal-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/dialog/dialog-non-modal-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dialog-reduce-motion-demo": {
    name: "dialog-reduce-motion-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["dialog"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/dialog/dialog-reduce-motion-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/dialog/dialog-reduce-motion-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dialog-scale-demo": {
    name: "dialog-scale-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["dialog"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/dialog/dialog-scale-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/dialog/dialog-scale-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dialog-top-flip-demo": {
    name: "dialog-top-flip-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["dialog"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/dialog/dialog-top-flip-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/dialog/dialog-top-flip-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dialog-bottom-flip-demo": {
    name: "dialog-bottom-flip-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["dialog"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/dialog/dialog-bottom-flip-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/dialog/dialog-bottom-flip-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dialog-left-flip-demo": {
    name: "dialog-left-flip-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["dialog"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/dialog/dialog-left-flip-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/dialog/dialog-left-flip-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dialog-right-flip-demo": {
    name: "dialog-right-flip-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["dialog"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/dialog/dialog-right-flip-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/dialog/dialog-right-flip-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dialog-top-slide-demo": {
    name: "dialog-top-slide-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["dialog"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/dialog/dialog-top-slide-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/dialog/dialog-top-slide-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dialog-bottom-slide-demo": {
    name: "dialog-bottom-slide-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["dialog"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/dialog/dialog-bottom-slide-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/dialog/dialog-bottom-slide-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dialog-left-slide-demo": {
    name: "dialog-left-slide-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["dialog"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/dialog/dialog-left-slide-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/dialog/dialog-left-slide-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dialog-right-slide-demo": {
    name: "dialog-right-slide-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["dialog"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/dialog/dialog-right-slide-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/dialog/dialog-right-slide-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dialog-fade-demo": {
    name: "dialog-fade-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["dialog"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/dialog/dialog-fade-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/dialog/dialog-fade-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dialog-wipe-demo": {
    name: "dialog-wipe-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["dialog"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/dialog/dialog-wipe-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/dialog/dialog-wipe-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "input-otp-demo": {
    name: "input-otp-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["input-otp"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/input-otp/input-otp-demo.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/input-otp/input-otp-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "input-otp-disabled-demo": {
    name: "input-otp-disabled-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["input-otp"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/input-otp/input-otp-disabled-demo.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/input-otp/input-otp-disabled-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "input-otp-sizes-demo": {
    name: "input-otp-sizes-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["input-otp"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/input-otp/input-otp-sizes-demo.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/input-otp/input-otp-sizes-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "input-otp-variants-demo": {
    name: "input-otp-variants-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["input-otp"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/input-otp/input-otp-variants-demo.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/input-otp/input-otp-variants-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "input-otp-separator-demo": {
    name: "input-otp-separator-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["input-otp"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/input-otp/input-otp-separator-demo.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/input-otp/input-otp-separator-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "input-otp-patterns-demo": {
    name: "input-otp-patterns-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["input-otp"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/input-otp/input-otp-patterns-demo.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/input-otp/input-otp-patterns-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "input-otp-controlled-demo": {
    name: "input-otp-controlled-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["input-otp"],
    dependencies: undefined,
    files: [{
      path: "src/registry/default/components/examples/input-otp/input-otp-controlled-demo.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/default/components/examples/input-otp/input-otp-controlled-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  }